export const queryKeys = {
  accounts:             () => ["accounts"],
  balances:             (params) => ["balances", params],
  transactions:         (params) => ["transactions", params],
  accountRegister:      (params) => ["accountRegister", params],
  tags:                 () => ["tags"],
  prices:               () => ["prices"],
  accountDeclarations:  () => ["accountDeclarations"],
  snapshots:            () => ["snapshots"],
  bankProfiles:         () => ["bankProfiles"],
  rules:                () => ["rules"],
  netWorthTimeseries:   (begin) => ["netWorthTimeseries", begin],
  imports:              () => ["imports"],
  importedTransactions: (batchId) => ["importedTransactions", batchId],
};
